### ISSUE TITLE
Gemma 2 output includes `<end_of_turn>`

### ISSUE THREAD

**Issue by DePasqualeOrg** [ml-explore/mlx-swift-examples#89] opened 2024-07-02 18:23 UTC
I noticed that the output from the Gemma 2 models always ends with `<end_of_turn>`. The Gemma 1.1 models don't have this problem. Any idea what could be causing it?

**Comment by awni** [comment] 2024-07-02 18:25
Can you give a prompt / settings to reproduce that?

**Comment by DePasqualeOrg** [comment] 2024-07-02 18:26
You can reproduce it with the LLMEval example app in this repo with any prompt and the default settings. Just set the model configuration like this:

```swift
let modelConfiguration = ModelConfiguration.gemma_2_9b_it_4bit
```

**Comment by DePasqualeOrg** [comment] 2024-07-02 18:29
Sorry, make sure to try a short prompt, like "1+1=".

**Comment by awni** [comment] 2024-07-02 18:42
Going by this: https://github.com/google/gemma.cpp/issues/276

It seems like that is expected now and needs to be processed by the user.

**Comment by awni** [comment] 2024-07-02 18:44
I don't think we should special case it in the example since it's very idiosyncratic, so I will close this. It should be fairly straightforward to trim the response if the last token is `<end_of_turn>`

**Closed by awni** 2024-07-02 18:44 UTC

**Comment by davidkoski** [comment] 2024-07-02 19:36
The evaluate function can take extra tokens to stop at (`extraEOSTokens`):

```
public func generate(
    promptTokens: [Int], parameters: GenerateParameters, model: LLMModel, tokenizer: Tokenizer,
    extraEOSTokens: Set<String>? = nil,
    didGenerate: ([Int]) async -> GenerateDisposition
```

and the model configuration holds the same (and it will be passed in with the current integrations:

```
    public static let phi34bit = ModelConfiguration(
        id: "mlx-community/Phi-3-mini-4k-instruct-4bit-no-q-embed",
        defaultPrompt: "what is the gravity on mars and the moon?",
        extraEOSTokens: ["<|end|>"]
```

**Comment by DePasqualeOrg** [comment] 2024-07-02 21:08
I tried using this before opening this issue, but it didn't work in this case.

**Comment by DePasqualeOrg** [comment] 2024-07-03 22:06
I did some [debugging](https://github.com/DePasqualeOrg/mlx-swift-examples/commit/7b1c7c126f4ea5260c0323eb832b88af435d9e61) in mlx-libraries, and the reason `extraEOSTokens` doesn't work here is that `<end_of_turn>` is being encoded as two tokens with Gemma 2, which causes it to be filtered out of the token IDs that would otherwise trigger the end of generation. Any idea why this token with ID 107 in [`tokenizer_config.json`](https://huggingface.co/mlx-community/gemma-2-9b-it-4bit/blob/main/tokenizer_config.json) for Gemma 2 would be parsed as two tokens?

**Comment by davidkoski** [comment] 2024-07-03 22:20
Ah, interesting -- I think some tokenizers are configured to prepend tokens.  See if something like this would work:

```
    // build a set of additional stop tokens
    let additionalEOSTokenIds = Set(
        (extraEOSTokens ?? [])
            .compactMap {
                tokenizer.convertTokenToId($0)
            })
```

That is probably a better way to do it anyway.
